### PR TITLE
Fix transfer

### LINKED ISSUE #19: Transfer doesn't seem to work in current `main`

### PR DESCRIPTION
**Pull request by tkiapril**
Resolves #19.
`@planetarium/account-raw` did not support private key with `0x` prefix. Also, a bug was fixed where self-to-self transfer was not working.

### CODE REVIEW

File: background/src/wallet/wallet.js [hunk 1]
```diff
@@ -101,9 +103,9 @@ export default class Wallet {
             },
         })).toString('hex');
 
-        let account = createAccount(wallet.privateKey);
+        let account = createAccount(wallet.privateKey.slice(2));
```
Comment (longfin) [inline background/src/wallet/wallet.js]:
```suggestion
        let account = createAccount(wallet.privateKey.replace('0x', ''));
```

I guess it may be more expressive.

**Review by longfin — APPROVED** [review]

**Review by dahlia — APPROVED** [review]
